# =====================================
# Frontend Dockerfile
# Author:Sujata Oak
# Uses NGINX Alpine image
# Copies static files to NGINX web root
# Exposes port 80
# =====================================

FROM nginx:alpine

COPY . /usr/share/nginx/html

EXPOSE 80
